// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transacao.proto
package com.carteiro.protos;

public final class TransacaoOuterClass {
  private TransacaoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CartaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Cartao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string numero_cartao = 1;</code>
     */
    java.lang.String getNumeroCartao();
    /**
     * <code>string numero_cartao = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumeroCartaoBytes();

    /**
     * <code>string nome_cartao = 2;</code>
     */
    java.lang.String getNomeCartao();
    /**
     * <code>string nome_cartao = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeCartaoBytes();

    /**
     * <code>string bandeira = 3;</code>
     */
    java.lang.String getBandeira();
    /**
     * <code>string bandeira = 3;</code>
     */
    com.google.protobuf.ByteString
        getBandeiraBytes();

    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    boolean hasVencimento();
    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    com.google.protobuf.Timestamp getVencimento();
    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getVencimentoOrBuilder();
  }
  /**
   * Protobuf type {@code Cartao}
   */
  public  static final class Cartao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Cartao)
      CartaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cartao.newBuilder() to construct.
    private Cartao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cartao() {
      numeroCartao_ = "";
      nomeCartao_ = "";
      bandeira_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cartao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              numeroCartao_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nomeCartao_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bandeira_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (vencimento_ != null) {
                subBuilder = vencimento_.toBuilder();
              }
              vencimento_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vencimento_);
                vencimento_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransacaoOuterClass.internal_static_Cartao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransacaoOuterClass.internal_static_Cartao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransacaoOuterClass.Cartao.class, TransacaoOuterClass.Cartao.Builder.class);
    }

    public static final int NUMERO_CARTAO_FIELD_NUMBER = 1;
    private volatile java.lang.Object numeroCartao_;
    /**
     * <code>string numero_cartao = 1;</code>
     */
    public java.lang.String getNumeroCartao() {
      java.lang.Object ref = numeroCartao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numeroCartao_ = s;
        return s;
      }
    }
    /**
     * <code>string numero_cartao = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumeroCartaoBytes() {
      java.lang.Object ref = numeroCartao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numeroCartao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_CARTAO_FIELD_NUMBER = 2;
    private volatile java.lang.Object nomeCartao_;
    /**
     * <code>string nome_cartao = 2;</code>
     */
    public java.lang.String getNomeCartao() {
      java.lang.Object ref = nomeCartao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeCartao_ = s;
        return s;
      }
    }
    /**
     * <code>string nome_cartao = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeCartaoBytes() {
      java.lang.Object ref = nomeCartao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeCartao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BANDEIRA_FIELD_NUMBER = 3;
    private volatile java.lang.Object bandeira_;
    /**
     * <code>string bandeira = 3;</code>
     */
    public java.lang.String getBandeira() {
      java.lang.Object ref = bandeira_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bandeira_ = s;
        return s;
      }
    }
    /**
     * <code>string bandeira = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBandeiraBytes() {
      java.lang.Object ref = bandeira_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bandeira_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VENCIMENTO_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp vencimento_;
    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    public boolean hasVencimento() {
      return vencimento_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    public com.google.protobuf.Timestamp getVencimento() {
      return vencimento_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : vencimento_;
    }
    /**
     * <code>.google.protobuf.Timestamp vencimento = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getVencimentoOrBuilder() {
      return getVencimento();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumeroCartaoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, numeroCartao_);
      }
      if (!getNomeCartaoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nomeCartao_);
      }
      if (!getBandeiraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bandeira_);
      }
      if (vencimento_ != null) {
        output.writeMessage(4, getVencimento());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumeroCartaoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, numeroCartao_);
      }
      if (!getNomeCartaoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nomeCartao_);
      }
      if (!getBandeiraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bandeira_);
      }
      if (vencimento_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getVencimento());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransacaoOuterClass.Cartao)) {
        return super.equals(obj);
      }
      TransacaoOuterClass.Cartao other = (TransacaoOuterClass.Cartao) obj;

      boolean result = true;
      result = result && getNumeroCartao()
          .equals(other.getNumeroCartao());
      result = result && getNomeCartao()
          .equals(other.getNomeCartao());
      result = result && getBandeira()
          .equals(other.getBandeira());
      result = result && (hasVencimento() == other.hasVencimento());
      if (hasVencimento()) {
        result = result && getVencimento()
            .equals(other.getVencimento());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMERO_CARTAO_FIELD_NUMBER;
      hash = (53 * hash) + getNumeroCartao().hashCode();
      hash = (37 * hash) + NOME_CARTAO_FIELD_NUMBER;
      hash = (53 * hash) + getNomeCartao().hashCode();
      hash = (37 * hash) + BANDEIRA_FIELD_NUMBER;
      hash = (53 * hash) + getBandeira().hashCode();
      if (hasVencimento()) {
        hash = (37 * hash) + VENCIMENTO_FIELD_NUMBER;
        hash = (53 * hash) + getVencimento().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransacaoOuterClass.Cartao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Cartao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Cartao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransacaoOuterClass.Cartao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Cartao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Cartao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransacaoOuterClass.Cartao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cartao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Cartao)
        TransacaoOuterClass.CartaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransacaoOuterClass.internal_static_Cartao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransacaoOuterClass.internal_static_Cartao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransacaoOuterClass.Cartao.class, TransacaoOuterClass.Cartao.Builder.class);
      }

      // Construct using TransacaoOuterClass.Cartao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numeroCartao_ = "";

        nomeCartao_ = "";

        bandeira_ = "";

        if (vencimentoBuilder_ == null) {
          vencimento_ = null;
        } else {
          vencimento_ = null;
          vencimentoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransacaoOuterClass.internal_static_Cartao_descriptor;
      }

      @java.lang.Override
      public TransacaoOuterClass.Cartao getDefaultInstanceForType() {
        return TransacaoOuterClass.Cartao.getDefaultInstance();
      }

      @java.lang.Override
      public TransacaoOuterClass.Cartao build() {
        TransacaoOuterClass.Cartao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransacaoOuterClass.Cartao buildPartial() {
        TransacaoOuterClass.Cartao result = new TransacaoOuterClass.Cartao(this);
        result.numeroCartao_ = numeroCartao_;
        result.nomeCartao_ = nomeCartao_;
        result.bandeira_ = bandeira_;
        if (vencimentoBuilder_ == null) {
          result.vencimento_ = vencimento_;
        } else {
          result.vencimento_ = vencimentoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransacaoOuterClass.Cartao) {
          return mergeFrom((TransacaoOuterClass.Cartao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransacaoOuterClass.Cartao other) {
        if (other == TransacaoOuterClass.Cartao.getDefaultInstance()) return this;
        if (!other.getNumeroCartao().isEmpty()) {
          numeroCartao_ = other.numeroCartao_;
          onChanged();
        }
        if (!other.getNomeCartao().isEmpty()) {
          nomeCartao_ = other.nomeCartao_;
          onChanged();
        }
        if (!other.getBandeira().isEmpty()) {
          bandeira_ = other.bandeira_;
          onChanged();
        }
        if (other.hasVencimento()) {
          mergeVencimento(other.getVencimento());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransacaoOuterClass.Cartao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransacaoOuterClass.Cartao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object numeroCartao_ = "";
      /**
       * <code>string numero_cartao = 1;</code>
       */
      public java.lang.String getNumeroCartao() {
        java.lang.Object ref = numeroCartao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          numeroCartao_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string numero_cartao = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumeroCartaoBytes() {
        java.lang.Object ref = numeroCartao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numeroCartao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string numero_cartao = 1;</code>
       */
      public Builder setNumeroCartao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        numeroCartao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string numero_cartao = 1;</code>
       */
      public Builder clearNumeroCartao() {
        
        numeroCartao_ = getDefaultInstance().getNumeroCartao();
        onChanged();
        return this;
      }
      /**
       * <code>string numero_cartao = 1;</code>
       */
      public Builder setNumeroCartaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        numeroCartao_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nomeCartao_ = "";
      /**
       * <code>string nome_cartao = 2;</code>
       */
      public java.lang.String getNomeCartao() {
        java.lang.Object ref = nomeCartao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeCartao_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome_cartao = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeCartaoBytes() {
        java.lang.Object ref = nomeCartao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeCartao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome_cartao = 2;</code>
       */
      public Builder setNomeCartao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nomeCartao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome_cartao = 2;</code>
       */
      public Builder clearNomeCartao() {
        
        nomeCartao_ = getDefaultInstance().getNomeCartao();
        onChanged();
        return this;
      }
      /**
       * <code>string nome_cartao = 2;</code>
       */
      public Builder setNomeCartaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nomeCartao_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bandeira_ = "";
      /**
       * <code>string bandeira = 3;</code>
       */
      public java.lang.String getBandeira() {
        java.lang.Object ref = bandeira_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bandeira_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bandeira = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBandeiraBytes() {
        java.lang.Object ref = bandeira_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bandeira_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bandeira = 3;</code>
       */
      public Builder setBandeira(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bandeira_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bandeira = 3;</code>
       */
      public Builder clearBandeira() {
        
        bandeira_ = getDefaultInstance().getBandeira();
        onChanged();
        return this;
      }
      /**
       * <code>string bandeira = 3;</code>
       */
      public Builder setBandeiraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bandeira_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp vencimento_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> vencimentoBuilder_;
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public boolean hasVencimento() {
        return vencimentoBuilder_ != null || vencimento_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public com.google.protobuf.Timestamp getVencimento() {
        if (vencimentoBuilder_ == null) {
          return vencimento_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : vencimento_;
        } else {
          return vencimentoBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public Builder setVencimento(com.google.protobuf.Timestamp value) {
        if (vencimentoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vencimento_ = value;
          onChanged();
        } else {
          vencimentoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public Builder setVencimento(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (vencimentoBuilder_ == null) {
          vencimento_ = builderForValue.build();
          onChanged();
        } else {
          vencimentoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public Builder mergeVencimento(com.google.protobuf.Timestamp value) {
        if (vencimentoBuilder_ == null) {
          if (vencimento_ != null) {
            vencimento_ =
              com.google.protobuf.Timestamp.newBuilder(vencimento_).mergeFrom(value).buildPartial();
          } else {
            vencimento_ = value;
          }
          onChanged();
        } else {
          vencimentoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public Builder clearVencimento() {
        if (vencimentoBuilder_ == null) {
          vencimento_ = null;
          onChanged();
        } else {
          vencimento_ = null;
          vencimentoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getVencimentoBuilder() {
        
        onChanged();
        return getVencimentoFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getVencimentoOrBuilder() {
        if (vencimentoBuilder_ != null) {
          return vencimentoBuilder_.getMessageOrBuilder();
        } else {
          return vencimento_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : vencimento_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp vencimento = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getVencimentoFieldBuilder() {
        if (vencimentoBuilder_ == null) {
          vencimentoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getVencimento(),
                  getParentForChildren(),
                  isClean());
          vencimento_ = null;
        }
        return vencimentoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Cartao)
    }

    // @@protoc_insertion_point(class_scope:Cartao)
    private static final TransacaoOuterClass.Cartao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransacaoOuterClass.Cartao();
    }

    public static TransacaoOuterClass.Cartao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cartao>
        PARSER = new com.google.protobuf.AbstractParser<Cartao>() {
      @java.lang.Override
      public Cartao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cartao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cartao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cartao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransacaoOuterClass.Cartao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransacaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transacao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id_transacao = 1;</code>
     */
    long getIdTransacao();

    /**
     * <code>float valor = 2;</code>
     */
    float getValor();

    /**
     * <code>string documento_cliente = 3;</code>
     */
    java.lang.String getDocumentoCliente();
    /**
     * <code>string documento_cliente = 3;</code>
     */
    com.google.protobuf.ByteString
        getDocumentoClienteBytes();

    /**
     * <code>string documento_servidor = 4;</code>
     */
    java.lang.String getDocumentoServidor();
    /**
     * <code>string documento_servidor = 4;</code>
     */
    com.google.protobuf.ByteString
        getDocumentoServidorBytes();

    /**
     * <code>string cidade_compra = 5;</code>
     */
    java.lang.String getCidadeCompra();
    /**
     * <code>string cidade_compra = 5;</code>
     */
    com.google.protobuf.ByteString
        getCidadeCompraBytes();

    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    boolean hasDataOperacao();
    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    com.google.protobuf.Timestamp getDataOperacao();
    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDataOperacaoOrBuilder();

    /**
     * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
     */
    int getTipoEstabelecimentoValue();
    /**
     * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
     */
    TransacaoOuterClass.Transacao.TipoEstabelecimento getTipoEstabelecimento();

    /**
     * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
     */
    int getTipoTransacaoValue();
    /**
     * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
     */
    TransacaoOuterClass.Transacao.TipoTransacao getTipoTransacao();
  }
  /**
   * Protobuf type {@code Transacao}
   */
  public  static final class Transacao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transacao)
      TransacaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transacao.newBuilder() to construct.
    private Transacao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transacao() {
      idTransacao_ = 0L;
      valor_ = 0F;
      documentoCliente_ = "";
      documentoServidor_ = "";
      cidadeCompra_ = "";
      tipoEstabelecimento_ = 0;
      tipoTransacao_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transacao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idTransacao_ = input.readInt64();
              break;
            }
            case 21: {

              valor_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              documentoCliente_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              documentoServidor_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cidadeCompra_ = s;
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (dataOperacao_ != null) {
                subBuilder = dataOperacao_.toBuilder();
              }
              dataOperacao_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dataOperacao_);
                dataOperacao_ = subBuilder.buildPartial();
              }

              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              tipoEstabelecimento_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              tipoTransacao_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransacaoOuterClass.internal_static_Transacao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransacaoOuterClass.internal_static_Transacao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransacaoOuterClass.Transacao.class, TransacaoOuterClass.Transacao.Builder.class);
    }

    /**
     * Protobuf enum {@code Transacao.TipoEstabelecimento}
     */
    public enum TipoEstabelecimento
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTOMOBILISTICO = 0;</code>
       */
      AUTOMOBILISTICO(0),
      /**
       * <code>SAUDE = 1;</code>
       */
      SAUDE(1),
      /**
       * <code>RURAL = 2;</code>
       */
      RURAL(2),
      /**
       * <code>ALIMENTACAO = 3;</code>
       */
      ALIMENTACAO(3),
      /**
       * <code>METALURGIA = 4;</code>
       */
      METALURGIA(4),
      /**
       * <code>TECNOLOGIA = 5;</code>
       */
      TECNOLOGIA(5),
      /**
       * <code>ENERGIA = 6;</code>
       */
      ENERGIA(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>AUTOMOBILISTICO = 0;</code>
       */
      public static final int AUTOMOBILISTICO_VALUE = 0;
      /**
       * <code>SAUDE = 1;</code>
       */
      public static final int SAUDE_VALUE = 1;
      /**
       * <code>RURAL = 2;</code>
       */
      public static final int RURAL_VALUE = 2;
      /**
       * <code>ALIMENTACAO = 3;</code>
       */
      public static final int ALIMENTACAO_VALUE = 3;
      /**
       * <code>METALURGIA = 4;</code>
       */
      public static final int METALURGIA_VALUE = 4;
      /**
       * <code>TECNOLOGIA = 5;</code>
       */
      public static final int TECNOLOGIA_VALUE = 5;
      /**
       * <code>ENERGIA = 6;</code>
       */
      public static final int ENERGIA_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TipoEstabelecimento valueOf(int value) {
        return forNumber(value);
      }

      public static TipoEstabelecimento forNumber(int value) {
        switch (value) {
          case 0: return AUTOMOBILISTICO;
          case 1: return SAUDE;
          case 2: return RURAL;
          case 3: return ALIMENTACAO;
          case 4: return METALURGIA;
          case 5: return TECNOLOGIA;
          case 6: return ENERGIA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TipoEstabelecimento>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TipoEstabelecimento> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TipoEstabelecimento>() {
              public TipoEstabelecimento findValueByNumber(int number) {
                return TipoEstabelecimento.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TransacaoOuterClass.Transacao.getDescriptor().getEnumTypes().get(0);
      }

      private static final TipoEstabelecimento[] VALUES = values();

      public static TipoEstabelecimento valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TipoEstabelecimento(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Transacao.TipoEstabelecimento)
    }

    /**
     * Protobuf enum {@code Transacao.TipoTransacao}
     */
    public enum TipoTransacao
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREDITO = 0;</code>
       */
      CREDITO(0),
      /**
       * <code>DEBITO = 1;</code>
       */
      DEBITO(1),
      /**
       * <code>VOUCHER = 2;</code>
       */
      VOUCHER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CREDITO = 0;</code>
       */
      public static final int CREDITO_VALUE = 0;
      /**
       * <code>DEBITO = 1;</code>
       */
      public static final int DEBITO_VALUE = 1;
      /**
       * <code>VOUCHER = 2;</code>
       */
      public static final int VOUCHER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TipoTransacao valueOf(int value) {
        return forNumber(value);
      }

      public static TipoTransacao forNumber(int value) {
        switch (value) {
          case 0: return CREDITO;
          case 1: return DEBITO;
          case 2: return VOUCHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TipoTransacao>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TipoTransacao> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TipoTransacao>() {
              public TipoTransacao findValueByNumber(int number) {
                return TipoTransacao.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TransacaoOuterClass.Transacao.getDescriptor().getEnumTypes().get(1);
      }

      private static final TipoTransacao[] VALUES = values();

      public static TipoTransacao valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TipoTransacao(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Transacao.TipoTransacao)
    }

    public static final int ID_TRANSACAO_FIELD_NUMBER = 1;
    private long idTransacao_;
    /**
     * <code>int64 id_transacao = 1;</code>
     */
    public long getIdTransacao() {
      return idTransacao_;
    }

    public static final int VALOR_FIELD_NUMBER = 2;
    private float valor_;
    /**
     * <code>float valor = 2;</code>
     */
    public float getValor() {
      return valor_;
    }

    public static final int DOCUMENTO_CLIENTE_FIELD_NUMBER = 3;
    private volatile java.lang.Object documentoCliente_;
    /**
     * <code>string documento_cliente = 3;</code>
     */
    public java.lang.String getDocumentoCliente() {
      java.lang.Object ref = documentoCliente_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentoCliente_ = s;
        return s;
      }
    }
    /**
     * <code>string documento_cliente = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDocumentoClienteBytes() {
      java.lang.Object ref = documentoCliente_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentoCliente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCUMENTO_SERVIDOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object documentoServidor_;
    /**
     * <code>string documento_servidor = 4;</code>
     */
    public java.lang.String getDocumentoServidor() {
      java.lang.Object ref = documentoServidor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentoServidor_ = s;
        return s;
      }
    }
    /**
     * <code>string documento_servidor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDocumentoServidorBytes() {
      java.lang.Object ref = documentoServidor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentoServidor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIDADE_COMPRA_FIELD_NUMBER = 5;
    private volatile java.lang.Object cidadeCompra_;
    /**
     * <code>string cidade_compra = 5;</code>
     */
    public java.lang.String getCidadeCompra() {
      java.lang.Object ref = cidadeCompra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cidadeCompra_ = s;
        return s;
      }
    }
    /**
     * <code>string cidade_compra = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCidadeCompraBytes() {
      java.lang.Object ref = cidadeCompra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cidadeCompra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_OPERACAO_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp dataOperacao_;
    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    public boolean hasDataOperacao() {
      return dataOperacao_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    public com.google.protobuf.Timestamp getDataOperacao() {
      return dataOperacao_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dataOperacao_;
    }
    /**
     * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDataOperacaoOrBuilder() {
      return getDataOperacao();
    }

    public static final int TIPO_ESTABELECIMENTO_FIELD_NUMBER = 7;
    private int tipoEstabelecimento_;
    /**
     * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
     */
    public int getTipoEstabelecimentoValue() {
      return tipoEstabelecimento_;
    }
    /**
     * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
     */
    public TransacaoOuterClass.Transacao.TipoEstabelecimento getTipoEstabelecimento() {
      @SuppressWarnings("deprecation")
      TransacaoOuterClass.Transacao.TipoEstabelecimento result = TransacaoOuterClass.Transacao.TipoEstabelecimento.valueOf(tipoEstabelecimento_);
      return result == null ? TransacaoOuterClass.Transacao.TipoEstabelecimento.UNRECOGNIZED : result;
    }

    public static final int TIPO_TRANSACAO_FIELD_NUMBER = 8;
    private int tipoTransacao_;
    /**
     * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
     */
    public int getTipoTransacaoValue() {
      return tipoTransacao_;
    }
    /**
     * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
     */
    public TransacaoOuterClass.Transacao.TipoTransacao getTipoTransacao() {
      @SuppressWarnings("deprecation")
      TransacaoOuterClass.Transacao.TipoTransacao result = TransacaoOuterClass.Transacao.TipoTransacao.valueOf(tipoTransacao_);
      return result == null ? TransacaoOuterClass.Transacao.TipoTransacao.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idTransacao_ != 0L) {
        output.writeInt64(1, idTransacao_);
      }
      if (valor_ != 0F) {
        output.writeFloat(2, valor_);
      }
      if (!getDocumentoClienteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, documentoCliente_);
      }
      if (!getDocumentoServidorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, documentoServidor_);
      }
      if (!getCidadeCompraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cidadeCompra_);
      }
      if (dataOperacao_ != null) {
        output.writeMessage(6, getDataOperacao());
      }
      if (tipoEstabelecimento_ != TransacaoOuterClass.Transacao.TipoEstabelecimento.AUTOMOBILISTICO.getNumber()) {
        output.writeEnum(7, tipoEstabelecimento_);
      }
      if (tipoTransacao_ != TransacaoOuterClass.Transacao.TipoTransacao.CREDITO.getNumber()) {
        output.writeEnum(8, tipoTransacao_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idTransacao_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, idTransacao_);
      }
      if (valor_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, valor_);
      }
      if (!getDocumentoClienteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, documentoCliente_);
      }
      if (!getDocumentoServidorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, documentoServidor_);
      }
      if (!getCidadeCompraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cidadeCompra_);
      }
      if (dataOperacao_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDataOperacao());
      }
      if (tipoEstabelecimento_ != TransacaoOuterClass.Transacao.TipoEstabelecimento.AUTOMOBILISTICO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, tipoEstabelecimento_);
      }
      if (tipoTransacao_ != TransacaoOuterClass.Transacao.TipoTransacao.CREDITO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, tipoTransacao_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransacaoOuterClass.Transacao)) {
        return super.equals(obj);
      }
      TransacaoOuterClass.Transacao other = (TransacaoOuterClass.Transacao) obj;

      boolean result = true;
      result = result && (getIdTransacao()
          == other.getIdTransacao());
      result = result && (
          java.lang.Float.floatToIntBits(getValor())
          == java.lang.Float.floatToIntBits(
              other.getValor()));
      result = result && getDocumentoCliente()
          .equals(other.getDocumentoCliente());
      result = result && getDocumentoServidor()
          .equals(other.getDocumentoServidor());
      result = result && getCidadeCompra()
          .equals(other.getCidadeCompra());
      result = result && (hasDataOperacao() == other.hasDataOperacao());
      if (hasDataOperacao()) {
        result = result && getDataOperacao()
            .equals(other.getDataOperacao());
      }
      result = result && tipoEstabelecimento_ == other.tipoEstabelecimento_;
      result = result && tipoTransacao_ == other.tipoTransacao_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_TRANSACAO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdTransacao());
      hash = (37 * hash) + VALOR_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValor());
      hash = (37 * hash) + DOCUMENTO_CLIENTE_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentoCliente().hashCode();
      hash = (37 * hash) + DOCUMENTO_SERVIDOR_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentoServidor().hashCode();
      hash = (37 * hash) + CIDADE_COMPRA_FIELD_NUMBER;
      hash = (53 * hash) + getCidadeCompra().hashCode();
      if (hasDataOperacao()) {
        hash = (37 * hash) + DATA_OPERACAO_FIELD_NUMBER;
        hash = (53 * hash) + getDataOperacao().hashCode();
      }
      hash = (37 * hash) + TIPO_ESTABELECIMENTO_FIELD_NUMBER;
      hash = (53 * hash) + tipoEstabelecimento_;
      hash = (37 * hash) + TIPO_TRANSACAO_FIELD_NUMBER;
      hash = (53 * hash) + tipoTransacao_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransacaoOuterClass.Transacao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Transacao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransacaoOuterClass.Transacao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransacaoOuterClass.Transacao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Transacao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransacaoOuterClass.Transacao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransacaoOuterClass.Transacao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transacao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transacao)
        TransacaoOuterClass.TransacaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransacaoOuterClass.internal_static_Transacao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransacaoOuterClass.internal_static_Transacao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransacaoOuterClass.Transacao.class, TransacaoOuterClass.Transacao.Builder.class);
      }

      // Construct using TransacaoOuterClass.Transacao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idTransacao_ = 0L;

        valor_ = 0F;

        documentoCliente_ = "";

        documentoServidor_ = "";

        cidadeCompra_ = "";

        if (dataOperacaoBuilder_ == null) {
          dataOperacao_ = null;
        } else {
          dataOperacao_ = null;
          dataOperacaoBuilder_ = null;
        }
        tipoEstabelecimento_ = 0;

        tipoTransacao_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransacaoOuterClass.internal_static_Transacao_descriptor;
      }

      @java.lang.Override
      public TransacaoOuterClass.Transacao getDefaultInstanceForType() {
        return TransacaoOuterClass.Transacao.getDefaultInstance();
      }

      @java.lang.Override
      public TransacaoOuterClass.Transacao build() {
        TransacaoOuterClass.Transacao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransacaoOuterClass.Transacao buildPartial() {
        TransacaoOuterClass.Transacao result = new TransacaoOuterClass.Transacao(this);
        result.idTransacao_ = idTransacao_;
        result.valor_ = valor_;
        result.documentoCliente_ = documentoCliente_;
        result.documentoServidor_ = documentoServidor_;
        result.cidadeCompra_ = cidadeCompra_;
        if (dataOperacaoBuilder_ == null) {
          result.dataOperacao_ = dataOperacao_;
        } else {
          result.dataOperacao_ = dataOperacaoBuilder_.build();
        }
        result.tipoEstabelecimento_ = tipoEstabelecimento_;
        result.tipoTransacao_ = tipoTransacao_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransacaoOuterClass.Transacao) {
          return mergeFrom((TransacaoOuterClass.Transacao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransacaoOuterClass.Transacao other) {
        if (other == TransacaoOuterClass.Transacao.getDefaultInstance()) return this;
        if (other.getIdTransacao() != 0L) {
          setIdTransacao(other.getIdTransacao());
        }
        if (other.getValor() != 0F) {
          setValor(other.getValor());
        }
        if (!other.getDocumentoCliente().isEmpty()) {
          documentoCliente_ = other.documentoCliente_;
          onChanged();
        }
        if (!other.getDocumentoServidor().isEmpty()) {
          documentoServidor_ = other.documentoServidor_;
          onChanged();
        }
        if (!other.getCidadeCompra().isEmpty()) {
          cidadeCompra_ = other.cidadeCompra_;
          onChanged();
        }
        if (other.hasDataOperacao()) {
          mergeDataOperacao(other.getDataOperacao());
        }
        if (other.tipoEstabelecimento_ != 0) {
          setTipoEstabelecimentoValue(other.getTipoEstabelecimentoValue());
        }
        if (other.tipoTransacao_ != 0) {
          setTipoTransacaoValue(other.getTipoTransacaoValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransacaoOuterClass.Transacao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransacaoOuterClass.Transacao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long idTransacao_ ;
      /**
       * <code>int64 id_transacao = 1;</code>
       */
      public long getIdTransacao() {
        return idTransacao_;
      }
      /**
       * <code>int64 id_transacao = 1;</code>
       */
      public Builder setIdTransacao(long value) {
        
        idTransacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id_transacao = 1;</code>
       */
      public Builder clearIdTransacao() {
        
        idTransacao_ = 0L;
        onChanged();
        return this;
      }

      private float valor_ ;
      /**
       * <code>float valor = 2;</code>
       */
      public float getValor() {
        return valor_;
      }
      /**
       * <code>float valor = 2;</code>
       */
      public Builder setValor(float value) {
        
        valor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float valor = 2;</code>
       */
      public Builder clearValor() {
        
        valor_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object documentoCliente_ = "";
      /**
       * <code>string documento_cliente = 3;</code>
       */
      public java.lang.String getDocumentoCliente() {
        java.lang.Object ref = documentoCliente_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          documentoCliente_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string documento_cliente = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDocumentoClienteBytes() {
        java.lang.Object ref = documentoCliente_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          documentoCliente_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string documento_cliente = 3;</code>
       */
      public Builder setDocumentoCliente(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        documentoCliente_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string documento_cliente = 3;</code>
       */
      public Builder clearDocumentoCliente() {
        
        documentoCliente_ = getDefaultInstance().getDocumentoCliente();
        onChanged();
        return this;
      }
      /**
       * <code>string documento_cliente = 3;</code>
       */
      public Builder setDocumentoClienteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        documentoCliente_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object documentoServidor_ = "";
      /**
       * <code>string documento_servidor = 4;</code>
       */
      public java.lang.String getDocumentoServidor() {
        java.lang.Object ref = documentoServidor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          documentoServidor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string documento_servidor = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDocumentoServidorBytes() {
        java.lang.Object ref = documentoServidor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          documentoServidor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string documento_servidor = 4;</code>
       */
      public Builder setDocumentoServidor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        documentoServidor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string documento_servidor = 4;</code>
       */
      public Builder clearDocumentoServidor() {
        
        documentoServidor_ = getDefaultInstance().getDocumentoServidor();
        onChanged();
        return this;
      }
      /**
       * <code>string documento_servidor = 4;</code>
       */
      public Builder setDocumentoServidorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        documentoServidor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cidadeCompra_ = "";
      /**
       * <code>string cidade_compra = 5;</code>
       */
      public java.lang.String getCidadeCompra() {
        java.lang.Object ref = cidadeCompra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cidadeCompra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cidade_compra = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCidadeCompraBytes() {
        java.lang.Object ref = cidadeCompra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cidadeCompra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cidade_compra = 5;</code>
       */
      public Builder setCidadeCompra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cidadeCompra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cidade_compra = 5;</code>
       */
      public Builder clearCidadeCompra() {
        
        cidadeCompra_ = getDefaultInstance().getCidadeCompra();
        onChanged();
        return this;
      }
      /**
       * <code>string cidade_compra = 5;</code>
       */
      public Builder setCidadeCompraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cidadeCompra_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dataOperacao_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dataOperacaoBuilder_;
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public boolean hasDataOperacao() {
        return dataOperacaoBuilder_ != null || dataOperacao_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public com.google.protobuf.Timestamp getDataOperacao() {
        if (dataOperacaoBuilder_ == null) {
          return dataOperacao_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dataOperacao_;
        } else {
          return dataOperacaoBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public Builder setDataOperacao(com.google.protobuf.Timestamp value) {
        if (dataOperacaoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataOperacao_ = value;
          onChanged();
        } else {
          dataOperacaoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public Builder setDataOperacao(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dataOperacaoBuilder_ == null) {
          dataOperacao_ = builderForValue.build();
          onChanged();
        } else {
          dataOperacaoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public Builder mergeDataOperacao(com.google.protobuf.Timestamp value) {
        if (dataOperacaoBuilder_ == null) {
          if (dataOperacao_ != null) {
            dataOperacao_ =
              com.google.protobuf.Timestamp.newBuilder(dataOperacao_).mergeFrom(value).buildPartial();
          } else {
            dataOperacao_ = value;
          }
          onChanged();
        } else {
          dataOperacaoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public Builder clearDataOperacao() {
        if (dataOperacaoBuilder_ == null) {
          dataOperacao_ = null;
          onChanged();
        } else {
          dataOperacao_ = null;
          dataOperacaoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDataOperacaoBuilder() {
        
        onChanged();
        return getDataOperacaoFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDataOperacaoOrBuilder() {
        if (dataOperacaoBuilder_ != null) {
          return dataOperacaoBuilder_.getMessageOrBuilder();
        } else {
          return dataOperacao_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dataOperacao_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp data_operacao = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDataOperacaoFieldBuilder() {
        if (dataOperacaoBuilder_ == null) {
          dataOperacaoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDataOperacao(),
                  getParentForChildren(),
                  isClean());
          dataOperacao_ = null;
        }
        return dataOperacaoBuilder_;
      }

      private int tipoEstabelecimento_ = 0;
      /**
       * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
       */
      public int getTipoEstabelecimentoValue() {
        return tipoEstabelecimento_;
      }
      /**
       * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
       */
      public Builder setTipoEstabelecimentoValue(int value) {
        tipoEstabelecimento_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
       */
      public TransacaoOuterClass.Transacao.TipoEstabelecimento getTipoEstabelecimento() {
        @SuppressWarnings("deprecation")
        TransacaoOuterClass.Transacao.TipoEstabelecimento result = TransacaoOuterClass.Transacao.TipoEstabelecimento.valueOf(tipoEstabelecimento_);
        return result == null ? TransacaoOuterClass.Transacao.TipoEstabelecimento.UNRECOGNIZED : result;
      }
      /**
       * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
       */
      public Builder setTipoEstabelecimento(TransacaoOuterClass.Transacao.TipoEstabelecimento value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tipoEstabelecimento_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Transacao.TipoEstabelecimento tipo_estabelecimento = 7;</code>
       */
      public Builder clearTipoEstabelecimento() {
        
        tipoEstabelecimento_ = 0;
        onChanged();
        return this;
      }

      private int tipoTransacao_ = 0;
      /**
       * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
       */
      public int getTipoTransacaoValue() {
        return tipoTransacao_;
      }
      /**
       * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
       */
      public Builder setTipoTransacaoValue(int value) {
        tipoTransacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
       */
      public TransacaoOuterClass.Transacao.TipoTransacao getTipoTransacao() {
        @SuppressWarnings("deprecation")
        TransacaoOuterClass.Transacao.TipoTransacao result = TransacaoOuterClass.Transacao.TipoTransacao.valueOf(tipoTransacao_);
        return result == null ? TransacaoOuterClass.Transacao.TipoTransacao.UNRECOGNIZED : result;
      }
      /**
       * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
       */
      public Builder setTipoTransacao(TransacaoOuterClass.Transacao.TipoTransacao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tipoTransacao_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Transacao.TipoTransacao tipo_transacao = 8;</code>
       */
      public Builder clearTipoTransacao() {
        
        tipoTransacao_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transacao)
    }

    // @@protoc_insertion_point(class_scope:Transacao)
    private static final TransacaoOuterClass.Transacao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransacaoOuterClass.Transacao();
    }

    public static TransacaoOuterClass.Transacao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transacao>
        PARSER = new com.google.protobuf.AbstractParser<Transacao>() {
      @java.lang.Override
      public Transacao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transacao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transacao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transacao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransacaoOuterClass.Transacao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cartao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cartao_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transacao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transacao_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017transacao.proto\032\037google/protobuf/times" +
      "tamp.proto\"v\n\006Cartao\022\025\n\rnumero_cartao\030\001 " +
      "\001(\t\022\023\n\013nome_cartao\030\002 \001(\t\022\020\n\010bandeira\030\003 \001" +
      "(\t\022.\n\nvencimento\030\004 \001(\0132\032.google.protobuf" +
      ".Timestamp\"\330\003\n\tTransacao\022\024\n\014id_transacao" +
      "\030\001 \001(\003\022\r\n\005valor\030\002 \001(\002\022\031\n\021documento_clien" +
      "te\030\003 \001(\t\022\032\n\022documento_servidor\030\004 \001(\t\022\025\n\r" +
      "cidade_compra\030\005 \001(\t\0221\n\rdata_operacao\030\006 \001" +
      "(\0132\032.google.protobuf.Timestamp\022<\n\024tipo_e" +
      "stabelecimento\030\007 \001(\0162\036.Transacao.TipoEst" +
      "abelecimento\0220\n\016tipo_transacao\030\010 \001(\0162\030.T" +
      "ransacao.TipoTransacao\"~\n\023TipoEstabeleci" +
      "mento\022\023\n\017AUTOMOBILISTICO\020\000\022\t\n\005SAUDE\020\001\022\t\n" +
      "\005RURAL\020\002\022\017\n\013ALIMENTACAO\020\003\022\016\n\nMETALURGIA\020" +
      "\004\022\016\n\nTECNOLOGIA\020\005\022\013\n\007ENERGIA\020\006\"5\n\rTipoTr" +
      "ansacao\022\013\n\007CREDITO\020\000\022\n\n\006DEBITO\020\001\022\013\n\007VOUC" +
      "HER\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Cartao_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Cartao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cartao_descriptor,
        new java.lang.String[] { "NumeroCartao", "NomeCartao", "Bandeira", "Vencimento", });
    internal_static_Transacao_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Transacao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transacao_descriptor,
        new java.lang.String[] { "IdTransacao", "Valor", "DocumentoCliente", "DocumentoServidor", "CidadeCompra", "DataOperacao", "TipoEstabelecimento", "TipoTransacao", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
